name: musllinux
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
jobs:
  musllinux:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python: [
          { version: '3.7', abi: 'cp37-cp37m' },
          { version: '3.8', abi: 'cp38-cp38' },
          { version: '3.9', abi: 'cp39-cp39' },
          { version: '3.10', abi: 'cp310-cp310' },
        ]
        platform:
          - target: aarch64-unknown-linux-musl
            arch: aarch64
          - target: armv7-unknown-linux-musleabihf
            arch: armv7
          - target: x86_64-unknown-linux-musl
            arch: x86_64
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python.version }}

    - run: |
        echo contents of
        pwd
        ls -l
        echo contents of dist
        ls -l dist/ || true
        echo contents of target
        ls -l target || true

    - name: Build wheels
      uses: messense/maturin-action@v1
      env:
        # PYO3_CROSS_LIB_DIR: /opt/python/${{ matrix.python.abi }}
        RUST_BACKTRACE: full
      with:
        rust-toolchain: nightly-2022-06-01
        target: ${{ matrix.platform.target }}
        manylinux: musllinux_1_1
        args: --release --strip --out dist --no-sdist --cargo-extra-args="--features=unstable-simd" -i python${{ matrix.python.version }}

    - name: Upload crash report
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: crash-report
        path: /tmp/report-*.toml

    - run: |
        echo contents of
        pwd
        ls -l
        echo contents of dist
        ls -l dist/ || true
        echo contents of target
        ls -l target || true


    # - name: Install built wheel
    #   if: matrix.platform.arch == 'x86_64'
    #   uses: addnab/docker-run-action@v3
    #   with:
    #     image: alpine:latest
    #     options: -v ${{ github.workspace }}:/io -w /io
    #     run: |
    #       apk add py3-pip
    #       pip3 install -U pip pytest
    #       pip3 install rjmespath --no-index --find-links /io/dist/ --force-reinstall
    #       cd tests && python3 -m pytest

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        image: tonistiigi/binfmt:qemu-v6.2.0
        platforms: all

    - name: Install built wheel
      # if: matrix.platform.arch == 'x86_64'
      uses: addnab/docker-run-action@v3
      with:
        # image: quay.io/pypa/musllinux_1_1_x86_64:latest
        image: quay.io/pypa/musllinux_1_1_${{ matrix.platform.arch }}:latest
        options: -v ${{ github.workspace }}:/io -w /io
        run: |
          # workaround zoneinfo._common.ZoneInfoNotFoundError: 'No time zone found with key UTC'
          # exception when running tests
          apk add tzdata

          # Don't install numpy since there are no musllinux wheels
          sed -i '/^numpy/d' test/requirements.txt

          PYTHON=python${{ matrix.python.version }}
          $PYTHON -m venv venv
          venv/bin/pip install -U pip
          venv/bin/pip install -r test/requirements.txt
          ls -l dist/
          venv/bin/pip install orjson --no-index --find-links dist/ --force-reinstall
          ls -l dist/
          venv/bin/python -m pytest -s -rxX -v test


    # - uses: uraimo/run-on-arch-action@master
    #   name: Install built wheel
    #   with:
    #     arch: ${{ matrix.platform.arch }}
    #     distro: alpine_latest
    #     githubToken: ${{ github.token }}
    #     install: |
    #       apk add py3-pip
    #       pip3 install -U pip pytest
    #     run: |
    #       pip3 install rjmespath --no-index --find-links dist/ --force-reinstall
    #       cd tests && python3 -m pytest

    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: dist

  release:
    name: Release
    runs-on: ubuntu-22.04
    if: "startsWith(github.ref, 'refs/tags/')"
    needs: [ musllinux ]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: wheels
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - run: pip install "maturin>=0.12.19,<0.13"
      - name: deploy
        run: maturin upload --skip-existing --username "$MATURIN_USERNAME" *.whl
        env:
          MATURIN_USERNAME: ${{ secrets.TWINE_USERNAME }}
          MATURIN_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
